# Анализ пространственно-временной динамики ареала лебедей в Северной Америке

---

## Тема проекта

**Анализ пространственно-временной динамики ареала лебедей в Северной Америке.**

---

## Цель проекта

Определить, наблюдается ли статистически значимое смещение ареала лебедей в Северной Америке, и выявить, различается ли это смещение в разных географических зонах. Оценить влияние внешних факторов (температура, плотность населения) на пространственное распределение птиц.

---

## Задачи проекта

1. Загрузить и очистить данные о наблюдениях за лебедями.
2. Добавить внешние данные (плотность населения и температура по штатам и провинциям).
3. Провести кластерный анализ для выделения географических зон.
4. Учесть сезонность и другие искажающие факторы.
5. Провести статистический анализ: оценить тренды, сравнить виды и сезоны.
6. Построить визуализации (не менее 4 графиков).
7. Сформулировать выводы.

---

# Описание датасетов

---

## 1. `short.csv` — наблюдения за лебедями

**Источник:** GBIF (Global Biodiversity Information Facility)

**Объём:** ~3.5 млн записей

| Столбец | Тип | Описание |
|---------|-----|----------|
| `gbifID` | int | Уникальный идентификатор наблюдения |
| `basisOfRecord` | str | Тип записи |
| `recordedBy` | str | Наблюдатель |
| `eventDate` | str | Дата наблюдения |
| `year` | int | Год |
| `month` | int | Месяц |
| `day` | int | День |
| `countryCode` | str | Код страны |
| `stateProvince` | str | Штат / провинция |
| `locality` | str | Локация |
| `decimalLatitude` | float | Широта |
| `decimalLongitude` | float | Долгота |
| `coordinateUncertaintyInMeters` | float | — |
| `coordinatePrecision` | float | — |
| `infraspecificEpithet` | float | — |
| `taxonRank` | str | Ранг таксона |
| `datasetKey` | str | Идентификатор источника |
| `elevation` | float | — |
| `elevationAccuracy` | float | — |
| `depth` | float | — |
| `depthAccuracy` | float | — |
| `species` | str | Вид |

**Виды в датасете:**
- `Cygnus olor` — лебедь-шипун
- `Cygnus buccinator` — лебедь-трубач
- `Cygnus columbianus` — американский тундровый лебедь
- `Cygnus atratus` — чёрный лебедь
- `Cygnus cygnus` — лебедь-кликун
- `Cygnus melancoryphus` — черношейный лебедь

---

## 2. `US_CA.csv` — плотность населения

**Объём:** 69 записей

| Столбец | Тип | Описание |
|---------|-----|----------|
| `state_province` | str | Название штата / провинции |
| `land_area` | float | Площадь, км² |
| `density_per` | float | Плотность населения, чел/км² |

---

## 3. `us_state_temperatures.csv` — температуры США

**Объём:** ~26 868 записей

| Столбец | Тип | Описание |
|---------|-----|----------|
| `state` | str | Название штата |
| `year` | int | Год |
| `month` | int | Месяц |
| `avg_temp_f` | float | Температура, °F |
| `avg_temp_c` | float | Температура, °C |

---

## 4. `canada_temperatures.csv` — температуры Канады

**Объём:** 6 864 записи

| Столбец | Тип | Описание |
|---------|-----|----------|
| `state_province` | str | Название провинции |
| `year` | int | Год |
| `month` | int | Месяц |
| `avg_temp_c` | float | Температура, °C |

---

# Задания по предобработке

Выполните следующие шаги в отдельных ячейках ноутбука.

---

### Блок 1. Загрузка и первичный осмотр

1. Загрузите `short.csv`.
2. Выведите `info()`, `shape` и список столбцов.
3. Проверьте количество пропусков по каждому столбцу.

### Блок 2. Очистка структуры данных

4. Удалите столбцы, полностью состоящие из пропусков.
5. Удалите столбец `locality`.
6. Приведите названия столбцов к формату `snake_case` (все буквы строчные, слова разделены `_`).
7. Преобразуйте столбец `event_date` в формат `datetime`.

### Блок 3. Фильтрация данных

8. Оставьте только три вида: `Cygnus olor`, `Cygnus buccinator`, `Cygnus columbianus`.
9. Оставьте только наблюдения из США и Канады (`US`, `CA`).
10. Проверьте и при необходимости ограничьте координаты: широта 25–75°, долгота −170…−35°.
11. Удалите столбцы с единственным уникальным значением.
12. Оставьте только годы **до 2023 включительно**.

### Блок 4. Обогащение данными

13. Загрузите `US_CA.csv`. Проверьте и приведите названия штатов/провинций к единому виду с основным датасетом.
14. Объедините основной датасет с данными о плотности населения.
15. Загрузите оба датасета с температурой.
16. Приведите температуры США и Канады к единому формату (названия столбцов, единицы измерения).
17. Объедините их в один датасет температур.
18. Проверьте уникальность пар `(state_province, year, month)`.

### Блок 5. Сезонная фильтрация

19. Оставьте только месяцы:
    - **Зимовка:** декабрь, январь, февраль
    - **Гнездование:** июнь, июль, август
20. Создайте столбец `period_type`: `1` для зимовки, `2` для гнездования.

### Блок 6. Временная разбивка

21. Разделите данные на 5 временных периодов:
    - `1_1980-1988`
    - `2_1989-1997`
    - `3_1998-2006`
    - `4_2007-2015`
    - `5_2016-2023`
22. Создайте столбец `time_period`.

### Блок 7. Работа с координатами и дубликатами

23. Округлите `decimal_latitude` и `decimal_longitude` до целых чисел.
24. Удалите дубликаты по набору `(year, period_type, decimal_longitude, decimal_latitude, species)`.

### Блок 8. Объединение с температурой

25. Объедините датасет с `temperatures_US_CA` по ключу `(state_province, year, month)`.
26. Проверьте пропуски в температуре. Заполните их средним значением по `(state_province, month)`.

### Блок 9. Сохранение и финальная проверка

27. Сохраните подготовленный датасет в `data_seasonal_enriched.csv`.
28. Выведите:
    - общее количество записей,
    - распределение по периодам,
    - распределение по видам,
    - среднюю температуру по сезонам,
    - среднюю широту по сезонам.

---

# Рекомендуемые статистические методы

Ниже — перечень методов, которые можно применять. Выбирайте в зависимости от вопроса.

---

### 1. Кластерный анализ (обязательно)

**Зачем:** разделить наблюдения на географические зоны.

**Пример:**
```python
from scipy.cluster.hierarchy import linkage, fcluster
from sklearn.preprocessing import StandardScaler

coords = df[['decimal_latitude', 'decimal_longitude']].values
coords_scaled = StandardScaler().fit_transform(coords)

linkage_matrix = linkage(coords_scaled, method='ward')
df['cluster'] = fcluster(linkage_matrix, t=5, criterion='maxclust')
```

---

### 2. Описательная статистика

**Зачем:** понять распределение данных по группам.

**Пример:**
```python
df.groupby('species')['decimal_latitude'].describe()
df.groupby('period_type')['avg_temp_c'].mean()
```

---

### 3. Линейная регрессия

**Зачем:** оценить, меняется ли широта со временем (тренд).

**Пример:**
```python
from scipy.stats import linregress

slope, intercept, r_value, p_value, std_err = linregress(df['year'], df['decimal_latitude'])
print(f"Наклон: {slope}, p-value: {p_value}, R²: {r_value**2}")
```

**Как читать:** если `p_value < 0.05` — тренд значим. Знак `slope` показывает направление.

---

### 4. Корреляционный анализ

**Зачем:** оценить связь между переменными.

**Пример:**
```python
from scipy.stats import pearsonr, spearmanr

r, p = pearsonr(df['avg_temp_c'], df['decimal_latitude'])
print(f"Пирсон: r = {r:.3f}, p = {p:.4f}")

rho, p = spearmanr(df['avg_temp_c'], df['decimal_latitude'])
print(f"Спирмен: ρ = {rho:.3f}, p = {p:.4f}")
```

**Как читать:** `p < 0.05` — связь значима. `r` показывает силу и направление.

---

### 5. Сравнение групп: Kruskal-Wallis

**Зачем:** проверить, различаются ли три и более групп (например, три вида).

**Пример:**
```python
from scipy.stats import kruskal

groups = [df[df['species'] == sp]['decimal_latitude'] for sp in df['species'].unique()]
stat, p = kruskal(*groups)
print(f"H = {stat:.2f}, p = {p:.4f}")
```

**Как читать:** если `p < 0.05` — группы различаются.

---

### 6. Попарные сравнения: Mann-Whitney U

**Зачем:** сравнить две конкретные группы.

**Пример:**
```python
from scipy.stats import mannwhitneyu

g1 = df[df['species'] == 'Cygnus olor']['decimal_latitude']
g2 = df[df['species'] == 'Cygnus buccinator']['decimal_latitude']
stat, p = mannwhitneyu(g1, g2, alternative='two-sided')
print(f"p = {p:.4f}")
```

---

### 7. Множественная регрессия

**Зачем:** оценить вклад нескольких факторов одновременно.

**Пример:**
```python
import statsmodels.api as sm

X = df[['year', 'avg_temp_c', 'density_per']]
X = sm.add_constant(X)
y = df['decimal_latitude']

model = sm.OLS(y, X).fit()
print(model.summary())
```

**Как читать:** смотрите на `p-value` каждого коэффициента и на `R²` модели.

---

### 8. Бутстрап (опционально)

**Зачем:** получить доверительные интервалы без предположения о нормальности.

**Пример:**
```python
import numpy as np

slopes = []
for _ in range(500):
    sample = df.sample(len(df), replace=True)
    slope = np.polyfit(sample['year'], sample['decimal_latitude'], 1)[0]
    slopes.append(slope)

ci_low, ci_high = np.percentile(slopes, [2.5, 97.5])
print(f"95% ДИ: [{ci_low:.4f}, {ci_high:.4f}]")
```

---

### 9. Шпаргалка: какой тест для какого вопроса

| Вопрос | Метод |
|--------|-------|
| Как разбить наблюдения на зоны? | Кластерный анализ |
| Есть ли тренд во времени? | Линейная регрессия |
| Связаны ли две переменные? | Корреляция (Пирсон/Спирмен) |
| Различаются ли группы? | Kruskal-Wallis |
| Различаются ли две группы? | Mann-Whitney U |
| Что важнее: год, температура, плотность? | Множественная регрессия |
| Как устойчив результат? | Бутстрап |

---

# Обязательные визуализации

Постройте минимум **4 графика** из списка:

1. **Карта кластеров** — точки на плоскости «долгота × широта», цвет — кластер.
2. **Дендрограмма** кластеризации.
3. **График тренда** — средняя широта по годам с линией регрессии (хотя бы для одного кластера).
4. **Boxplot** — сравнение широты или температуры по видам.
5. **Тепловая карта корреляций**.
6. **Диаграмма рассеяния** — широта vs температура.

---

# Критерии оценки

| № | Критерий | Баллы |
|---|----------|-------|
| 1 | Данные загружены и очищены | 1 |
| 2 | Обрезка по годам и фильтрация выполнены | 1 |
| 3 | Обогащение данными (плотность, температура) выполнено | 1 |
| 4 | Сезонная фильтрация и разбиение на периоды выполнены | 1 |
| 5 | Кластерный анализ выполнен, выделено 5 кластеров | 1 |
| 6 | Построено минимум 4 визуализации | 1 |
| 7 | Применён хотя бы один статистический тест | 1 |
| 8 | Выводы сформулированы | 1 |
| 9 | Датасет сохранён в CSV | 1 |
| **Итого** | | **9** |

---

# Формат итогового отчёта

Ноутбук должен содержать:

1. Введение (цель, задачи, данные).
2. Предобработку данных (код + краткие пояснения).
3. Обогащение данными.
4. Кластерный анализ.
5. Статистический анализ.
6. Визуализации.
7. Выводы (что удалось выяснить, ограничения).

---

# ЧАСТЬ 2. КОД (шаблон для заполнения)

---

## 1. Загрузка библиотек

In [68]:
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
import seaborn as sns

from scipy.stats import linregress, kruskal, mannwhitneyu, pearsonr, spearmanr
from scipy.cluster.hierarchy import linkage, dendrogram, fcluster
from sklearn.preprocessing import StandardScaler
import statsmodels.api as sm
from statsmodels.formula.api import ols

sns.set_style('whitegrid')

## 2. Загрузка данных

In [69]:
data = pd.read_csv('short.csv')
data.info()
print(data.shape)
print(data.isna().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3489498 entries, 0 to 3489497
Data columns (total 22 columns):
 #   Column                         Dtype
---  ------                         -----
 0   gbifID                         int64
 1   basisOfRecord                  object
 2   recordedBy                     object
 3   eventDate                      object
 4   year                           int64
 5   month                          int64
 6   day                            int64
 7   countryCode                    object
 8   stateProvince                  object
 9   locality                       object
 10  decimalLatitude                float64
 11  decimalLongitude               float64
 12  coordinateUncertaintyInMeters  float64
 13  coordinatePrecision            float64
 14  infraspecificEpithet           float64
 15  taxonRank                      object
 16  datasetKey                     object
 17  elevation                      float64
 18  elevationAccuracy              float64
 19  depth                          float64
 20  depthAccuracy                  float64
 21  species                        object
dtypes: float64(9), int64(4), object(9)
memory usage: 585.7+ MB
(3489498, 22)
gbifID                                 0
basisOfRecord                          0
recordedBy                             0
eventDate                              0
year                                   0
month                                  0
day                                    0
countryCode                            0
stateProvince                          0
locality                               4
decimalLatitude                        0
decimalLongitude                       0
coordinateUncertaintyInMeters    3489498
coordinatePrecision              3489498
infraspecificEpithet             3489498
taxonRank                              0
datasetKey                             0
elevation                        3489498
elevationAccuracy                3489498
depth                            3489498
depthAccuracy                    3489498
species                                0
dtype: int64

В загруженом  датасете имеются пропуски всех значений в семи столбцах, эти столбцы можно удалить, так же имеется 4 пропуска в столбце locality.

## 3. Удаление пустых столбцов

> TODO: удалите столбцы, полностью состоящие из пропусков, и столбец `locality`.

In [70]:
# Удалим столбцы с пропусками
data = data.drop(columns=['locality', 'coordinateUncertaintyInMeters', 'coordinatePrecision', 'infraspecificEpithet', 'elevation', 'elevationAccuracy', 'depth', 'depthAccuracy'])

In [71]:
# Проведем проверку корректности удаления
data.info()
print(data.isna().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3489498 entries, 0 to 3489497
Data columns (total 14 columns):
 #   Column            Dtype
---  ------            -----
 0   gbifID            int64
 1   basisOfRecord     object
 2   recordedBy        object
 3   eventDate         object
 4   year              int64
 5   month             int64
 6   day               int64
 7   countryCode       object
 8   stateProvince     object
 9   decimalLatitude   float64
 10  decimalLongitude  float64
 11  taxonRank         object
 12  datasetKey        object
 13  species           object
dtypes: float64(2), int64(4), object(8)
memory usage: 372.7+ MB
gbifID              0
basisOfRecord       0
recordedBy          0
eventDate           0
year                0
month               0
day                 0
countryCode         0
stateProvince       0
decimalLatitude     0
decimalLongitude    0
taxonRank           0
datasetKey          0
species             0
dtype: int64

После проверки видим, что столбцов с пропусками не осталось

## 4. Переименование столбцов в snake_case

> TODO: примените функцию `camel_to_snake` ко всем столбцам.

In [72]:
# Перименум столбцы
def camel_to_snake(name):
    '''Преобразует CamelCase в snake_case.'''
    s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
    return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).lower()

data.columns = [camel_to_snake(col) for col in data.columns]

In [73]:
# Проверим результат
print(data.columns.tolist())

['gbif_id', 'basis_of_record', 'recorded_by', 'event_date', 'year', 'month', 'day', 'country_code', 'state_province', 'decimal_latitude', 'decimal_longitude', 'taxon_rank', 'dataset_key', 'species']

## 5. Преобразование типа event_date

> TODO: приведите `event_date` к `datetime`.

In [74]:
# Приведем столбец event_date к формату datetime
data['event_date'] = pd.to_datetime(data['event_date'])

## 6. Фильтрация данных

> TODO:
> - оставить только три вида: `Cygnus olor`, `Cygnus buccinator`, `Cygnus columbianus`;
> - оставить только US и CA;
> - ограничить координаты (широта 25–75°, долгота −170…−35°);
> - удалить столбцы с единственным уникальным значением.

In [75]:
# Отфильтруем данные 
species_list = ['Cygnus olor', 'Cygnus buccinator', 'Cygnus columbianus']
country_list = ['US', 'CA']

data = data[
    data['species'].isin(species_list) &
    data['country_code'].isin(country_list) &
    data['decimal_latitude'].between(25, 75) &
    data['decimal_longitude'].between(-170, -35)
]

constant_cols = data.columns[data.nunique() == 1]
print("Константные столбцы:", constant_cols.tolist())

data = data.drop(columns=constant_cols)

Константные столбцы: ['basis_of_record', 'taxon_rank', 'dataset_key']

In [76]:
# Проведем проверку оставшихся данных
print(data.shape)
print(data.nunique())

(3477414, 11)
gbif_id              3477414
recorded_by           133457
event_date             16041
year                      45
month                     12
day                       31
country_code               2
state_province            62
decimal_latitude      326558
decimal_longitude     331078
species                    3
dtype: int64

## 7. Обрезка по годам

> TODO: оставьте только `year <= 2023`.

In [77]:
data = data[data['event_date'] < '2024-01-01']

In [78]:
print(data.head())
print("Пропуски в датафрейме data:", data.isna().sum())

      gbif_id  recorded_by event_date  year  month  day country_code  \
0   938888072   obsr137539 2008-01-19  2008      1   19           US
1  3511818940   obsr902368 2021-01-23  2021      1   23           US
3  3264353040   obsr305952 2020-05-28  2020      5   28           CA
4  3630533474  obsr1312860 2021-09-09  2021      9    9           CA
5  3244141543    obsr58975 2020-05-29  2020      5   29           CA

    state_province  decimal_latitude  decimal_longitude            species
0    Massachusetts         42.041756          -70.19348        Cygnus olor
1    Massachusetts         42.222797          -72.60885        Cygnus olor
3          Ontario         43.231647          -81.91111        Cygnus olor
4          Ontario         43.155900          -79.17696  Cygnus buccinator
5  Yukon Territory         60.424446         -134.24268  Cygnus buccinator
Пропуски в датафрейме data: gbif_id              0
recorded_by          0
event_date           0
year                 0
month                0
day                  0
country_code         0
state_province       0
decimal_latitude     0
decimal_longitude    0
species              0
dtype: int64

Мы провели очистку и фильтрацию данных датасета date с данными наблюдения за лебедями. В результате у нас осталось 11 столбцов с данными до 2024 года, пропусков нет.

## 8. Загрузка внешних данных

> TODO:
> - загрузите `US_CA.csv`, `us_state_temperatures.csv`, `canada_temperatures.csv`;
> - приведите названия штатов и провинций к единому виду;
> - приведите датасеты температур к единому формату.

In [79]:
df_US_CA = pd.read_csv('US_CA.csv')
us_temperatures = pd.read_csv('us_state_temperatures.csv')
ca_temperatures = pd.read_csv('canada_temperatures.csv')

df_US_CA.head()

         state_province  land_area  density_per
0  District of Columbia      158.0       4297.0
1            New Jersey    19047.0        488.0
2          Rhode Island     2678.0        409.0
3           Puerto Rico     8868.0        361.0
4         Massachusetts    20202.0        347.0

In [80]:
us_temperatures.head()

     state  year  month  avg_temp_f  avg_temp_c
0  Alabama  1980      1        46.7    8.166667
1  Alabama  1980      2        42.7    5.944444
2  Alabama  1980      3        52.6   11.444444
3  Alabama  1980      4        60.6   15.888889
4  Alabama  1980      5        70.2   21.222222

In [81]:
ca_temperatures.head()

  state_province  year  month  avg_temp_c
0        Alberta  1980      1  -15.833060
1        Alberta  1980      2   -8.911123
2        Alberta  1980      3   -6.203974
3        Alberta  1980      4    7.940524
4        Alberta  1980      5   11.229850

In [82]:
# Поменяем название колонки с провициями в Канаде
us_temperatures = us_temperatures.rename(columns={'state': 'state_province'})
print(us_temperatures.columns.tolist())

['state_province', 'year', 'month', 'avg_temp_f', 'avg_temp_c']

In [83]:
# Удалим колонку с температурой в F
us_temperatures = us_temperatures.drop(columns=['avg_temp_f'])
print(us_temperatures.columns.tolist())

['state_province', 'year', 'month', 'avg_temp_c']

В результате преобразований мы получили таблицы с соответствующими названиями колонок и средней температурой в градусах Цельсия.

In [84]:
# Объединим два датафрейма с температурой в один
temperatures_US_CA = pd.concat([us_temperatures, ca_temperatures], ignore_index=True)
print(temperatures_US_CA.head())

  state_province  year  month  avg_temp_c
0        Alabama  1980      1    8.166667
1        Alabama  1980      2    5.944444
2        Alabama  1980      3   11.444444
3        Alabama  1980      4   15.888889
4        Alabama  1980      5   21.222222

## 9. Сезонная фильтрация

> TODO:
> - оставьте только декабрь, январь, февраль и июнь, июль, август;
> - создайте столбец `period_type` (1 = зимовка, 2 = гнездование).

In [85]:
# Оставляем только зиму и лето
months = [12, 1, 2, 6, 7, 8]

data = data[
    data['month'].isin(months)
].copy().reset_index(drop=True)

In [86]:
# Разделяем зима и лето на соответственно зимовка и гнездование
month_to_period = {
    12: 1, 1: 1, 2: 1,   # зимовка
    6: 2, 7: 2, 8: 2,    # гнездование
}

data['period_type'] = data['month'].map(month_to_period)

In [87]:
print(data.head())

      gbif_id  recorded_by event_date  year  month  day country_code  \
0   938888072   obsr137539 2008-01-19  2008      1   19           US
1  3511818940   obsr902368 2021-01-23  2021      1   23           US
2  1708517102    obsr46830 2016-01-03  2016      1    3           US
3  5349334195  obsr6752262 2023-01-19  2023      1   19           US
4  2035949122   obsr379975 2017-01-21  2017      1   21           CA

     state_province  decimal_latitude  decimal_longitude             species  \
0     Massachusetts         42.041756          -70.19348         Cygnus olor
1     Massachusetts         42.222797          -72.60885         Cygnus olor
2          Michigan         42.653122          -85.49594   Cygnus buccinator
3          Virginia         37.825560          -76.80855  Cygnus columbianus
4  British Columbia         50.171513         -116.95749   Cygnus buccinator

   period_type
0            1
1            1
2            1
3            1
4            1

## 10. Разбивка на временные периоды

> TODO: создайте столбец `time_period` с 5 интервалами:
> `1_1980-1988`, `2_1989-1997`, `3_1998-2006`, `4_2007-2015`, `5_2016-2023`.

In [88]:
# Разделяем на пять периодов

bins = [1979, 1988, 1997, 2006, 2015, 2023]
labels = ['1_1980-1988', '2_1989-1997', '3_1998-2006', '4_2007-2015', '5_2016-2023']

data['time_period'] = pd.cut(
    data['year'],
    bins=bins,
    labels=labels,
    include_lowest=True
)

In [89]:
print(data.head())

      gbif_id  recorded_by event_date  year  month  day country_code  \
0   938888072   obsr137539 2008-01-19  2008      1   19           US
1  3511818940   obsr902368 2021-01-23  2021      1   23           US
2  1708517102    obsr46830 2016-01-03  2016      1    3           US
3  5349334195  obsr6752262 2023-01-19  2023      1   19           US
4  2035949122   obsr379975 2017-01-21  2017      1   21           CA

     state_province  decimal_latitude  decimal_longitude             species  \
0     Massachusetts         42.041756          -70.19348         Cygnus olor
1     Massachusetts         42.222797          -72.60885         Cygnus olor
2          Michigan         42.653122          -85.49594   Cygnus buccinator
3          Virginia         37.825560          -76.80855  Cygnus columbianus
4  British Columbia         50.171513         -116.95749   Cygnus buccinator

   period_type  time_period
0            1  4_2007-2015
1            1  5_2016-2023
2            1  5_2016-2023
3            1  5_2016-2023
4            1  5_2016-2023

## 11. Округление координат и удаление дубликатов

> TODO: округлите координаты до целых и удалите дубликаты по набору
> `(year, period_type, decimal_longitude, decimal_latitude, species)`.

In [90]:
# Округляем координаты до целых
for col in ['decimal_latitude', 'decimal_longitude']:
    data[col] = data[col].round().astype(int)

In [91]:
print(data[['decimal_latitude', 'decimal_longitude']].dtypes)
print(data[['decimal_latitude', 'decimal_longitude']].head())

decimal_latitude     int64
decimal_longitude    int64
dtype: object
   decimal_latitude  decimal_longitude
0                42                -70
1                42                -73
2                43                -85
3                38                -77
4                50               -117

In [92]:
# Удаляем дубликаты 
set_columns = ['year', 'period_type', 'decimal_longitude', 'decimal_latitude', 'species']

before = len(data)
data = data.drop_duplicates(subset=set_columns).reset_index(drop=True)
after = len(data)

print(f"Было: {before}")
print(f"Стало: {after}")
print(f"Удалено дубликатов: {before - after}")

Было: 1289670
Стало: 33095
Удалено дубликатов: 1256575

## 12. Объединение с температурой

> TODO:
> - объедините датасет с `temperatures_US_CA` по ключу `(state_province, year, month)`;
> - заполните пропуски температуры средним значением по `(state_province, month)`.

In [93]:
print("Пропуски в датафрейме data:", data.isna().sum())

Пропуски в датафрейме data: gbif_id              0
recorded_by          0
event_date           0
year                 0
month                0
day                  0
country_code         0
state_province       0
decimal_latitude     0
decimal_longitude    0
species              0
period_type          0
time_period          0
dtype: int64

In [ ]:
#  Объединяем датафреймы
data_temp = data.merge(
    temperatures_US_CA,
    on=['state_province', 'year', 'month'],
    how='left'
)

print("До заполнения пропусков в avg_temp_c:", data_temp['avg_temp_c'].isna().sum())

# 2. Заполняем средним по (state_province, month)
data_temp['avg_temp_c'] = data_temp['avg_temp_c'].fillna(
    data_temp.groupby(['state_province', 'month'])['avg_temp_c'].transform('mean')
)

print("После заполнения:", data_temp['avg_temp_c'].isna().sum())
print(data_temp.head())
print(data_temp.shape)

До заполнения пропусков в avg_temp_c: 3185
После заполнения: 3185
      gbif_id  recorded_by event_date  year  month  day country_code  \
0   938888072   obsr137539 2008-01-19  2008      1   19           US
1  3511818940   obsr902368 2021-01-23  2021      1   23           US
2  1708517102    obsr46830 2016-01-03  2016      1    3           US
3  5349334195  obsr6752262 2023-01-19  2023      1   19           US
4  2035949122   obsr379975 2017-01-21  2017      1   21           CA

     state_province  decimal_latitude  decimal_longitude             species  \
0     Massachusetts                42                -70         Cygnus olor
1     Massachusetts                42                -73         Cygnus olor
2          Michigan                43                -85   Cygnus buccinator
3          Virginia                38                -77  Cygnus columbianus
4  British Columbia                50               -117   Cygnus buccinator

   period_type  time_period  avg_temp_c
0            1  4_2007-2015   -2.111111
1            1  5_2016-2023   -1.777778
2            1  5_2016-2023   -5.388889
3            1  5_2016-2023    5.944444
4            1  5_2016-2023   -3.185258
(33095, 14)

## 13. Сохранение датасета

> TODO: сохраните подготовленный датасет в `data_seasonal_enriched.csv`.

In [95]:
# Ваш код здесь

## 14. Финальная проверка

> TODO: выведите:
> - общее количество записей;
> - распределение по периодам;
> - распределение по видам;
> - среднюю температуру по сезонам;
> - среднюю широту по сезонам.

In [96]:
# Ваш код здесь

## 15. Кластерный анализ

> TODO: агрегируйте данные по ячейкам (широта + долгота),
> стандартизируйте координаты, примените метод Уорда,
> выделите 5 кластеров.

In [97]:
# Ваш код здесь

## 16. Описательная статистика по кластерам

> TODO: выведите среднюю широту, температуру и число записей
> по каждому кластеру.

In [98]:
# Ваш код здесь

## 17. Линейная регрессия по кластерам

> TODO: для каждого кластера постройте тренд широты по годам
> и выведите `slope`, `R²`, `p-value`.

In [99]:
# Ваш код здесь

## 18. Корреляционный анализ

> TODO: посчитайте корреляцию:
> - широта vs температура (в целом и по сезонам);
> - широта vs плотность населения.

In [100]:
# Ваш код здесь

## 19. Сравнение групп (Kruskal-Wallis, Mann-Whitney)

> TODO:
> - сравните виды по широте и температуре;
> - сравните сезоны по широте;
> - проведите попарные сравнения видов.

In [101]:
# Ваш код здесь

## 20. Множественная регрессия

> TODO: постройте модель `decimal_latitude ~ year + avg_temp_c + density_per`.
> Выведите коэффициенты, `R²`, `p-value`.

In [102]:
# Ваш код здесь

## 21. Визуализации

> TODO: постройте минимум 4 графика:
> 1. карта кластеров;
> 2. дендрограмма;
> 3. график тренда широты;
> 4. boxplot по видам.

In [103]:
# Ваш код здесь

## 22. Выводы

> TODO: сформулируйте выводы в текстовом блоке:
> - наблюдается ли смещение ареала?
> - различается ли оно по кластерам?
> - какие различия между видами и сезонами?
> - какие ограничения анализа?

In [104]:
# Ваш код здесь